### ISSUE TITLE
Installation commands for Raspbian

### ISSUE THREAD

**Issue by villamann** [jvmahon/homebridge-homeseer-jrhubott#1]
Hi! I have installed your 2018-version and it works perfectly. Thank you for your effort.
The one thing troubling me is my garage-port. I use a FGS-222 relay switch to trigger the garage opener and a FGK-101 door sensor to determine open/closed status. I have tried without luck to get this solution working with the parameters available in 2018-version. So I decided to try the parallel solution, and then use my old config file for the garage. Unfortunately due to my limited linux-skills I haven`t been able to install the homebridge-homeseer-jrhubott plug-in, could you help out with the right command(s) needed (for Raspbian) to achieve parallel use of the two?

**Comment by jvmahon** [comment]
Rather than try to do the dual-plugin solution, can you send me the accessory line from your old config.json that you used to use for your garage door and explain which parameter you need that's currently missing from the -2018 plugin. If its reasonably easy to do,  I may be able to add it to the -2018 plugin so you won't need to use both plugins.

**Comment by villamann** [comment]
Cool, my old config was:
`       {
          "ref":93,
          "type":"GarageDoorOpener",
          "name":"Garasje",
          "stateRef":113,
          "statusUpdateCount":15,
          "stateOpenValues":[
            255
          ],
          "stateClosedValues":[
            0
          ],
          "controlRef":93,
          "controlOpenValue":255,
          "controlCloseValue":255,
          "uuid_base":"Garasjeport"
        }`
where ref 93 is the FGS-222 and stateRef 113 is the FGK-101. It is the state ref parameter i am lacking, cause my solution does not have any obstruction sensor. And since all the FGS-222 do is shortcut two inputs on the motor, both controlOpenValue and controlCloseValue is 255, with an auto-off set to 0,1 sec. in the FGS-222`s settings.

**Comment by villamann** [comment]
It works! I was sure I had tested just that particular config line before my previous post, apparantly not correctly.
Thanks a lot for helping out with this, and thank you for a super plug-in! 

P.S: Regarding 1), just if you want to chase my error. When I enter the command `npm -g install homebridge-homeseer-jrhubott.git`, this is the output:
![bilde](https://user-images.githubusercontent.com/1861423/38962306-e59e8764-436c-11e8-9b2c-3b74a0a77833.png)
And when I enter `npm -g install git://github.com/jvmahon/homebridge-homseer-jrhubott`, this is the output:
![bilde](https://user-images.githubusercontent.com/1861423/38962237-a39aace4-436c-11e8-8b29-c66d2f3cef2f.png)

**Comment by jvmahon** [comment]
Glad it is now working.

As for the two-plugin solution, from your error report, I now see the problem! there was a typo in my Wiki instructions which I've now corrected. You must have been the first person to have ever tried to use the two-plugin solution as nobody ever reported the error before. The problem was in the plugin name I had spelled "homeseer" as "homseer" - i.e., it was missing an 'e'. So the correct install instruction should have been to execute:

    npm -g install git://github.com/jvmahon/homebridge-homeseer-jrhubott
